### ISSUE TITLE
tags 2.4.0 is missing

### ISSUE THREAD

**Issue by carlosrodfern** [csmith-project/csmith#171]
I noticed that Fedora has version 2.4.0 in its repo, and the source were pulled from this github project originally, however, the tag 2.4.0 is not listed in the tags in this project. The last one is 2.3.0.

Was 2.4.0 reverted? Would it be back?

**Comment by eeide** [comment]
Hi! To my knowledge, we (the Csmith authors) have not made an actual Csmith 2.4.0 release. That's why there's no tag (or branch) corresponding to the release.

The tag was not removed, because it never existed.

The current `master`-branch Csmith source identifies itself as version 2.4.0, because our (my) convention when making releases was to (1) make a branch for maintaining the release, e.g., the `csmith-2.3` branch, (2) put release tags along that branch, e.g., `csmith-2.3.0`, and then (3) increment the version number on the `master` branch. So the version number on the master branch was the version we were working toward.

Given this situation, and the amount of time since we designated the 2.3.0 release, I suppose it is "sensible" that some Fedora package-maker might have made something that they call version 2.4.0. But they did that, not us.

**Comment by carlosrodfern** [comment]
@eeide: thank you for the clarification.
