### ISSUE TITLE
Dereferencing a non-volatile pointer to a Union/struct which contains a volatile field 

### ISSUE THREAD

**Issue by jxyang** [csmith-project/csmith#74]
The following code illustrate the idea:
```c
struct S0 {
   uint8_t  f0;
   const volatile uint64_t  f1;
   const uint8_t  f2;
};

union U1 {
   struct S0  f0;
   uint32_t  f1;
   uint64_t  f2;
   uint32_t  f3;
   uint32_t  f4;
};

static union U1 g_881 = {{0x88L,18446744073709551609UL,0UL}};/* VOLATILE GLOBAL g_881 */
static union U1 *g_1998 = &g_881;     // illegal?
...
... = *g_1998                         // will compiler optimize the read?
```

It seems to me that even though neither U1 nor S0 is declared as volatile, the fact that field f1 of S0 is volatile makes KCC think it's illegal to take the address of g_881 and pass it to a non-volatile pointer g_1998. I am not sure whether this is a truthful interpretation of the C standard. @John Regehr , what do you think?

The underlying question is that when g_1998 is dereferenced, does the compiler know that it should not optimize the read even though g_1998 itself is declared as non-volatile? If the compiler is smart enough to look into declarations of U1 and recursively S0, it should know the read is not to be optimized. Otherwise,  it's a bug of Csmith.

Thanks Radu for the test case.

**Comment by jxyang** [comment]
@regehr

**Comment by Quuxplusone** [comment]
The line `static union U1 *g_1998 = &g_881;` is definitely 100% legal C, and if the tool complains about it, the tool is wrong.

But the line `= *g_1998` is problematic in practice.

Volatile data members are generally a horrible idea, IMHO. The C++ (WG21) paper [P1153R0 "Copying volatile subobjects is not trivial"](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1153r0.html) is related.

[This godbolt example](https://godbolt.org/z/CC_fX_) shows that both GCC and Clang will optimize 

```
typedef struct {
    volatile int a;
    volatile short b;
    volatile char c;
} S;
void foo(S *a, S *b) {
    *a = *b;
}
```

to load 8 bytes at a time, rather than issuing 4-byte, 2-byte, and 1-byte volatile loads.

In C++, `S` is "trivially copyable," meaning that it can portably be copied using `memcpy`, even though `memcpy` may copy a byte at a time, which causes tearing. I haven't figured out a way to get the C compiler to generate tearing loads (e.g. load `volatile int a` via a pair of `movw` instructions instead of a single `movl` instruction), but I bet it's possible, somehow, in practice.

Programmers who use `volatile` on individual data members are operating in a state of sin, and I think the best guarantee they can hope for is that their compiler won't outright crash. Hoping for some specific codegen is a fool's hope. I wouldn't shed any tears if Csmith didn't try to test their runtime behavior.

**Comment by jxyang** [comment]
To be clear, the tool kcc was complaining about the last line `... = *g_1998`. Now it makes sense to me as the compilers apparently don't separate out the read on the volatile field (even though they could in theory). Therefore this is confirmed a Csmith bug. 

Thanks for the explanation, @Quuxplusone
