### ISSUE TITLE
Turn on c++14 in the compiler

### ISSUE THREAD

**Issue by jxyang** [csmith-project/csmith#81]
Looking at the [build log ](https://travis-ci.org/csmith-project/csmith/builds/581626469?utm_source=github_status&utm_medium=notification), we are using clang 5.0 which defaults to c++98. We should either:

* upgrade to [clang 6.0](https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-60-CPP14)  so it defaults to c++14, or
* tell travis to add `-std=c++14` while using the compiler.

**Comment by eeide** [comment]
As of commit 900729a, this issue should be resolved for the CMake-based build path.

The CMake-based build path now specifies C++14 for `csmith`. In addition, the Travis-CI build uses `bionic`, Ubuntu 18.04, which has Clang 7.0.

This issue is not yet resolved for the Automake-bsed build path. We don't us the Automake-based path for the CI builds, so updating that path is less critical, but I hope to try to address it soon. ("Soon" is at least few weeks away, however, because I need to prepare a talk and do some travel in the next few weeks.)

**Comment by jxyang** [comment]
Thanks Eric.
